title: Requirements
description: Requirements for the game
theme: just-the-docs

url: https://taraaliz.github.io/sunsettara-docs

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/taraaliz/sunsettara-docs
